"""empty message

Revision ID: 55bde635e277
Revises: f5aea274adba
Create Date: 2024-11-21 14:27:43.281098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55bde635e277'
down_revision: Union[str, None] = 'f5aea274adba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_history')
    op.drop_table('contract')
    op.drop_table('user')
    op.drop_table('item')
    op.drop_table('favourites')
    op.drop_table('feedback')
    op.add_column('items', sa.Column('time', sa.String(length=50), nullable=True))
    op.alter_column('items', 'owner',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'items', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'items', 'users', ['owner'], ['id'])
    op.alter_column('items', 'owner',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('items', 'time')
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('grade', sa.INTEGER(), nullable=False),
    sa.Column('contract', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('favourites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.INTEGER(), nullable=False),
    sa.Column('item', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user')
    )
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('photo', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price_hour', sa.REAL(), nullable=True),
    sa.Column('price_day', sa.REAL(), nullable=True),
    sa.Column('price_week', sa.REAL(), nullable=True),
    sa.Column('price_month', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('login', sa.TEXT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('ipn', sa.INTEGER(), nullable=True),
    sa.Column('full_name', sa.TEXT(), nullable=False),
    sa.Column('contacs', sa.TEXT(), nullable=False),
    sa.Column('photo', sa.TEXT(), nullable=False),
    sa.Column('passport', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('contract',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('start_date', sa.TEXT(), nullable=False),
    sa.Column('end_date', sa.TEXT(), nullable=False),
    sa.Column('leaser', sa.INTEGER(), nullable=False),
    sa.Column('taker', sa.INTEGER(), nullable=False),
    sa.Column('item', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('search_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.INTEGER(), nullable=False),
    sa.Column('search_text', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user')
    )
    # ### end Alembic commands ###
